version: 2
updates:
  - package-ecosystem: npm
    directory: /node-stack
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      nestjs:
        patterns:
          - '@nestjs/*'
      drizzle:
        patterns:
          - drizzle*
      eslint:
        patterns:
          - eslint*
          - '@typescript-eslint/*'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
