/* eslint-disable */
// Auto-generated by @nestjs/swagger CLI plugin.
// Regenerate with: npx ts-node -r tsconfig-paths/register node_modules/.bin/nest-metadata
// Currently disabled (nest-cli.json plugins: []) — using a no-op export.
export default async () => {
    return { "@nestjs/swagger": { "models": [], "controllers": [] } };
};